apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: 605789054429.dkr.ecr.us-east-1.amazonaws.com/e-commerce-app:latest
          ports:
            - containerPort: 5000
