apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  annotations:
    # Tell AWS ALB target group to use pod IPs
    service.beta.kubernetes.io/aws-load-balancer-target-type: "ip"
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000
