Name: AWS_ACCESS_KEY_ID
Value: AKIAY2C6XMXOYGL3IEWY

Name: AWS_SECRET_ACCESS_KEY
Value: <your secret key>

Name: AWS_REGION
Value: us-east-1

Name: SLACK_WEBHOOK_URL
Value: https://hooks.slack.com/services/whatever

Name: ECR_REPO
Value: 123456789012.dkr.ecr.us-east-1.amazonaws.com/my-app
